name: zhanggui_pos
description: 这个项目是一个开源的POS系统，非常方便在手机上使用。
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  geocoder: any
  get: ^4.6.5
  flutter_localizations:
    sdk: flutter
  permission_handler: ^10.3.0
  shared_preferences: ^2.0.8
  flutter_dotenv: ^5.0.2
  logger: ^1.0.0
  location: ^4.4.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  animated_notch_bottom_bar: ^0.0.6
  timeline_list: ^0.0.6
  sqflite: ^2.2.7
  path: ^1.8.0
  avatar_glow: ^2.0.2
  flutter_markdown: ^0.6.8
  http: ^0.13.5
  dart_mock: ^2.0.0
  get_storage: ^2.1.1
  flutter_share: ^2.0.0
  webview_flutter: ^3.0.3
  url_launcher: ^6.0.9
  sm_crypto: ^1.0.3
  uuid: ^3.0.7
  flutter_rating_bar: ^4.0.1
  speech_to_text: ^6.1.1
  cupertino_icons: ^1.0.2
  intro_slider: ^2.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path: "assets/app.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/app.png
    - assets/scanner.png
    - assets/inventory.png
    - assets/info.png
    - assets/background.png
