name: zhanggui_pos
description: 这个项目是一个开源的POS系统，非常方便在手机上使用。
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  geocoder: any
  get: ^4.6.5
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0
  intl: ^0.17.0
  permission_handler: ^10.3.0
  flutter_dotenv: ^5.0.2
  logger: ^1.0.0
  latlong2: ^0.8.0
  google_maps_flutter: ^2.2.5
  location: ^4.4.0
  flutter_polyline_points: ^1.0.0
  geolocator: ^9.0.2
  flutter_map: ^3.1.0
  geocoding: ^2.1.0
  animated_notch_bottom_bar: ^0.0.6
  timeline_list: ^0.0.6
  sqflite: ^2.2.7
  path: ^1.8.0
  avatar_glow: ^2.0.2
  flutter_markdown: ^0.6.8
  http: ^0.13.5
  firebase_analytics: ^10.2.0
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  sign_in_with_apple: ^4.3.0
  dart_mock: ^2.0.0
  get_storage: ^2.1.1
  internet_connection_checker: ^1.0.0+1
  google_sign_in: any
  firebase_performance: ^0.9.1
  map_launcher: ^2.5.0+1
  flutter_svg: any
  flutter_share: ^2.0.0
  webview_flutter: ^3.0.3
  url_launcher: ^6.0.9
  parse_server_sdk_flutter: ^4.0.0
  sm_crypto: ^1.0.3
  uuid: ^3.0.7
  flutter_rating_bar: ^4.0.1
  flutter_typeahead: ^3.1.3
  flutter_google_places: ^0.3.0
  firebase_database: ^10.1.1
  speech_to_text: ^6.1.1
  floating_draggable_widget: ^2.1.2
  fl_baidu_mob_stat: ^1.3.1+1
  loading_animation_widget: ^1.2.0+4
  draggable_bottom_sheet: ^1.0.2
  sliding_up_panel: ^2.0.0+1
  measured_size: ^1.0.0
  pubspec_parse: ^1.2.3
  onesignal_flutter: ^3.5.1
  just_audio: 0.9.34
  audio_session: ^0.1.16
  google_mlkit_text_recognition: any
  app_tracking_transparency: ^2.0.4
  device_info_plus: ^9.0.2
  package_info_plus: ^3.1.2
  restart_app: ^1.1.2
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
